name: bump-version 
on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Bump version type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          pip install bumpver
          bumpver update --${{ inputs.type }}
      - run: |
          git push -u origin && git push -u origin --tags
