name: publish


on:
  release:
    types:
      - published

jobs:

  publish-package:
    if: github.event_name == 'release'

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
          pip install ".[tests]"
      - name: build-package
        run: hatch build

      - name: publish-package
        run: hatch publish --user __token__ --auth $PYPI_TOKEN
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
