name: Create Sphinx documentation
on: [push]
jobs:
  build:
    name: Sphinx Pages
    runs-on: ubuntu-latest
    steps:
      - uses: toniher/sphinx-pages@patch-1
        id: sphinx-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_readme: true
          source_dir: docs