name: Run test pipeline
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    environment: CI
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          python-version: 3.9
          environment-file: environment.yml
          mamba-version: "*"
          activate-environment: krisi
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
          use-mamba: true
      - name: Install local module krisi
        shell: bash -l {0}
        run: |
          pip install -e .
      - uses: iterative/setup-cml@v1
      - name: Run pytest
        shell: bash -l {0}
        run: |
          pytest -s --junit-xml pytest.xml
      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results (Python ${{ matrix.python-version }})
          path: pytest.xml
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: pytest.xml